<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Srinivass-MacBook-Air.local" failures="0" tests="6" name="testcases.TC2_Loginddt" time="123.438" errors="1" timestamp="2024-12-06T15:55:39 GMT" skipped="0">
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="12.706"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="21.969"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="24.141"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="21.755"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="21.880"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="20.987">
    <error message="Cannot invoke &quot;pageobjects.LoginPage.setEmail(String)&quot; because &quot;loginPage&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageobjects.LoginPage.setEmail(String)" because "loginPage" is null
at testcases.TC2_Loginddt.testLogin(TC2_Loginddt.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </error>
  </testcase> <!-- testLogin -->
</testsuite> <!-- testcases.TC2_Loginddt -->
